/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class AccountValidation extends javax.swing.JPanel{

//    this holds the account no len
    private int AccNoLen;
    
    
//    this holds the AccountNo
    private long AccNo;
    
  
//    this holds No of failure Attempt user made?
    private int attempt ;
    
    //this hold wether the account is exist or not
    boolean isExist=false;
    
    
    
    /**
     * Creates new form Welcome
     */
    public AccountValidation() {
        initComponents();
       attempt = ApplicationManager.getAttempt();
       AccNoLen = 1;
//       nextButton.setEnabled(false);
       
       
////       whene the page load Input field get focus
//        AccountNo.setText(null);
//       AccountNo.grabFocus();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AccountNo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(88, 173, 255));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 244, 244));
        jLabel1.setText("EasyMoneyTrans");

        jLabel3.setBackground(new java.awt.Color(242, 242, 242));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Next: Enetr SecretKey.... ");

        nextButton.setBackground(new java.awt.Color(139, 214, 255));
        nextButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 244, 244));
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Go-Button.png"))); // NOI18N
        nextButton.setText("Go..");
        nextButton.setBorder(null);
        nextButton.setBorderPainted(false);
        nextButton.setContentAreaFilled(false);
        nextButton.setEnabled(false);
        nextButton.setFocusPainted(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        nextButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nextButtonKeyReleased(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(139, 214, 255));
        jSeparator1.setForeground(new java.awt.Color(139, 214, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("divider"); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/atm-card-insert.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("OR ");

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel5.setText("Enter Your Account No");

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel6.setText("Swip Your Card");

        AccountNo.setBackground(new java.awt.Color(139, 214, 255));
        AccountNo.setColumns(19);
        AccountNo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        AccountNo.setForeground(new java.awt.Color(255, 255, 255));
        AccountNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AccountNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AccountNo.setDisabledTextColor(new java.awt.Color(88, 173, 255));
        AccountNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AccountNoFocusGained(evt);
            }
        });
        AccountNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AccountNoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(174, 174, 174)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(nextButton)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(208, 208, 208)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1036, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(241, 241, 241)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5)
                        .addGap(65, 65, 65)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextButton)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel4))
                .addGap(137, 137, 137))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(499, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(291, 291, 291)))
        );

        AccountNo.getAccessibleContext().setAccessibleName("AccountNo");
        AccountNo.getAccessibleContext().setAccessibleDescription("this field holds the account no ");
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        
//        ??when nextButton clicked
            
        
            try{
                isExist = ApplicationManager.DBManager.c.isCustomerExist(AccNo);
                
                ApplicationManager.incrementAttempt();
                
                if(isExist)
                {
                  ApplicationManager.setAttempt(0);
                  ApplicationManager.application.loadScene(new KeyValidation()); 
                  
                }
                else if(attempt < 3){

                    ApplicationManager.application.loadScene(new AccountValidation());
                    ApplicationManager.Notify.sendNotification("Invalid Account no",1);
                }
                else{
                    
                    ApplicationManager.application.loadScene(new Welcome());
                    
                    
                }
                
                
            }catch(Exception e)
            {
                System.out.println(e);
            }
        
        
        
    
        
        
        
        System.out.println("Accountvalidation button clicked   " + attempt);
        
    }//GEN-LAST:event_nextButtonActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formKeyReleased

    private void nextButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nextButtonKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_nextButtonKeyReleased

    private void AccountNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AccountNoKeyReleased
        // TODO add your handling code here:
        
         JTextField an = (JTextField)evt.getSource();
        
//        System.out.println("hii");
        
        try{
            if(AccNoLen != 1)
            {
                AccNo = Long.parseLong(an.getText());
            }
        }catch(Exception e)
        {
            System.out.println("error in accno");
        }
        
        AccNoLen =  an.getText().length() ;
        
        if(AccNoLen >= 19)
        {
            System.out.println("20 exceed");
            an.setEnabled(false);
            nextButton.setEnabled(true);
            ApplicationManager.DBManager.cust.AccountNo = AccNo;
            
        }
    }//GEN-LAST:event_AccountNoKeyReleased

    private void AccountNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AccountNoFocusGained
        // TODO add your handling code here:
        
        ApplicationManager.Notify.hide();
    }//GEN-LAST:event_AccountNoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
